# Generated by Django 4.1.7 on 2023-05-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='like',
            field=models.ManyToManyField(blank=True, to='account.customer'),
        ),
    ]
